# Generated by Django 3.1.4 on 2022-09-02 13:39

from django.db import migrations, models
import django_countries.fields
import personal_information.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spokenlanguage',
            options={'ordering': ['language']},
        ),
        migrations.AddField(
            model_name='mentorpersonalinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorpersonalinformation',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='documents/cv'),
        ),
        migrations.AddField(
            model_name='mentorpersonalinformation',
            name='have_experience_tutoring_agency_or_online',
            field=models.IntegerField(blank=True, choices=[(0, 'NO'), (1, 'YES')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='mentorpersonalinformation',
            name='name_of_agency_or_online_platforms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorpersonalinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='current_or_last_school_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuserpersonalinformation',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='user_profile/'),
        ),
        migrations.AlterField(
            model_name='studentpersonalinformation',
            name='study_destination',
            field=django_countries.fields.CountryField(blank=True, countries=personal_information.models.DestinationCountries, max_length=35, multiple=True),
        ),
    ]
