# Generated by Django 3.2.5 on 2021-10-27 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='User Name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent_string', models.TextField(blank=True, verbose_name='User Agent String')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('choices_provided', models.TextField(blank=True, verbose_name='Choices provided')),
                ('choices_accepted', models.TextField(blank=True, verbose_name='Choices accepted')),
                ('choices_json', models.TextField(blank=True, verbose_name='Choices in JSON')),
                ('verification_hash', models.CharField(help_text='MD5 hash of this record, Django Secret Key, and the hash of previous log entry.', max_length=32, verbose_name='Verification Hash')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cookie Consent Record',
                'verbose_name_plural': 'Cookie Consent Logs',
            },
        ),
    ]
