# Generated by Django 4.2.16 on 2024-09-15 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaypalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("amount_charged", models.FloatField()),
                ("currency", models.CharField(max_length=5)),
                ("payer_paypal_name", models.CharField(max_length=50)),
                ("payepayer_paypal_email", models.EmailField(max_length=50)),
                ("paid_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaypalOnboardedSeller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paypal_merchant_id", models.CharField(max_length=50)),
                ("paypal_account_status", models.CharField(max_length=30)),
                ("permission_granted", models.BooleanField(default=False)),
                ("consent_status", models.BooleanField(default=False)),
                ("paypal_account_email_confirmed", models.BooleanField(default=False)),
                ("onboarded_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
