# Generated by Django 3.1.4 on 2022-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('appointment_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
