# Generated by Django 3.1.4 on 2022-10-03 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_customuser_how_did_you_hear_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
