# Generated by Django 3.2 on 2023-03-28 15:43

import AFM.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20221130_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockuser',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='user_profile/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveIntegerField(choices=[('', 'select-user'), (0, 'Super admin'), (1, 'Admin'), (2, 'Institute'), (3, 'Student'), (4, 'Mentor'), (5, 'Parent'), (6, 'Institute admin'), (7, 'App admin'), (8, 'Recruiter'), (9, 'System Mentor'), (10, 'System Recruiter'), (11, 'School')], null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_logo',
            field=models.ImageField(blank=True, null=True, upload_to='institute_logo/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instituterecruiterworkwith',
            name='agreement_doc',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='instituterecruiterworkwith',
            name='agreement_end_year',
            field=models.IntegerField(choices=[('', 'Select'), (2023, 2023), (2024, 2024)], default=2023, null=True),
        ),
        migrations.AlterField(
            model_name='instituterecruiterworkwith',
            name='agreement_start_year',
            field=models.IntegerField(choices=[('', 'Select'), (2023, 2023), (2024, 2024)], default=2023, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='intake_year',
            field=models.IntegerField(choices=[('', 'Select')], default=2023, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='institute_logo',
            field=models.FileField(blank=True, null=True, upload_to='institute_logo/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='recruiters/passports/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='user_profile/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='recruiters/registration_certificate/', validators=[AFM.validators.validate_file_size]),
        ),
    ]
