# Generated by Django 4.2.16 on 2024-09-15 15:19

import AFM.validators
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("sub_title", ckeditor.fields.RichTextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "feature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="page_feature_image/",
                        validators=[AFM.validators.validate_file_size],
                    ),
                ),
                (
                    "post_status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Publish")], default=0, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_page",
                        to="page.page",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
