# Generated by Django 3.1.4 on 2022-11-28 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='sub_title',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
