# Generated by Django 3.2 on 2023-03-28 15:51

import AFM.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20221128_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_feature_image/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
