# Generated by Django 3.1.4 on 2022-07-01 07:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_lead_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('sub_title', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('feature_image', models.ImageField(null=True, upload_to='blog_feature_image/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('publish', models.BooleanField(default=False, null=True)),
                ('post_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Submit for Review'), (2, 'Publish')], default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='administration.mentor')),
            ],
            options={
                'verbose_name': 'post_image',
                'verbose_name_plural': 'post_images',
                'ordering': ['-created_on'],
            },
        ),
    ]
