# Generated by Django 3.2 on 2023-03-28 15:47

import AFM.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20230328_1643'),
        ('blogs', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='administration.mentor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(null=True, upload_to='blog_feature_image/', validators=[AFM.validators.validate_file_size]),
        ),
    ]
