# Generated by Django 3.1.4 on 2022-09-02 13:32

import application.models
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220630_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='study_destination_country',
            field=django_countries.fields.CountryField(countries=application.models.DestinationCountries, default='GB', max_length=35, multiple=True),
        ),
    ]
