# Generated by Django 3.2 on 2023-03-28 15:47

import AFM.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20221130_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exclude_institutes_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='level_of_english',
            field=models.IntegerField(choices=[('', 'Select'), (0, 'Beginners'), (1, 'Elementary'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Native Speaker')], null=True),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='certificate_doc_url',
            field=models.FileField(blank=True, null=True, upload_to='academic-qualification-certificates/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='course_duration_from_year',
            field=models.IntegerField(choices=[('', 'Select'), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='course_duration_to_year',
            field=models.IntegerField(choices=[('', 'Select'), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True),
        ),
        migrations.AlterField(
            model_name='academicqualification',
            name='transcripts_doc_url',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='intake_year',
            field=models.IntegerField(choices=[('', 'Select'), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032)], default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='portfolios/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='research_portfolio',
            field=models.FileField(null=True, upload_to='research-portfolios/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='applicationappliedatuniversitylogin',
            name='application_doc',
            field=models.FileField(blank=True, null=True, upload_to='email-applications/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='consideredapplication',
            name='application_doc',
            field=models.FileField(blank=True, null=True, upload_to='email-applications/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='upload',
            field=models.FileField(null=True, upload_to='application-document-uploads/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='englishlanguage',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='english-language-certificates/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='finalselected',
            name='proof_of_payment',
            field=models.FileField(null=True, upload_to='proof-of-payments/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='duration_from_year',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='duration_to_year',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True),
        ),
        migrations.AlterField(
            model_name='professionaltrainingcertificate',
            name='certificate_url',
            field=models.FileField(blank=True, null=True, upload_to='professional-training-certificates/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='reference',
            name='duration_from_year',
            field=models.IntegerField(choices=[('', 'Select'), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='duration_to_year',
            field=models.IntegerField(choices=[('', 'Select'), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_upload',
            field=models.FileField(blank=True, null=True, upload_to='references/', validators=[AFM.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='visahistory',
            name='visa_duration_from_year',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AlterField(
            model_name='visahistory',
            name='visa_duration_to_year',
            field=models.IntegerField(blank=True, choices=[('', 'Select'), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
    ]
