# Generated by Django 3.1.4 on 2022-04-14 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_reportuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraiseUserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='reason_to_report',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PraiseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('praise_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='praised_by', to=settings.AUTH_USER_MODEL)),
                ('praised_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='praised_user', to=settings.AUTH_USER_MODEL)),
                ('reason_to_praise', models.ManyToManyField(to='messaging.PraiseUserChoice')),
            ],
        ),
    ]
