# Generated by Django 4.2.16 on 2024-09-15 15:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "All Users"),
                            (2, "Institute"),
                            (3, "Student"),
                            (4, "Mentor"),
                            (5, "Parent"),
                            (6, "Institute admin"),
                            (7, "App admin"),
                            (8, "Recruiter"),
                            (9, "System Mentor"),
                            (10, "System Recruiter"),
                        ],
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", ckeditor.fields.RichTextField()),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("publish", "Publish"), ("draft", "Draft")],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faqs.faqcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
