# Generated by Django 3.2 on 2023-03-28 15:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20221130_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(0, 'All Users'), (2, 'Institute'), (3, 'Student'), (4, 'Mentor'), (5, 'Parent'), (6, 'Institute admin'), (7, 'App admin'), (8, 'Recruiter'), (9, 'System Mentor'), (10, 'System Recruiter')], null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faqs.faqcategory'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
