# Generated by Django 4.2.16 on 2024-09-15 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(blank=True, max_length=3000, null=True),
                ),
                (
                    "Details",
                    models.TextField(default="I am scheduling an appointment for..."),
                ),
                (
                    "InitiateRefund",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("cost", models.PositiveIntegerField(default=20)),
                ("currency", models.CharField(default="USD", max_length=5)),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointment",
            },
        ),
        migrations.CreateModel(
            name="Reasons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Reason", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Reasons",
                "verbose_name_plural": "Reasons",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField(max_length=250)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved", models.BooleanField(default=False)),
                ("denial_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Services",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="UserServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to="bookings.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timeslots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("date", models.DateField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Timeslots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeslots",
                "verbose_name_plural": "Timeslots",
            },
        ),
        migrations.CreateModel(
            name="AppointmentCancelRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.appointment",
                    ),
                ),
                (
                    "Mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Cancellation request",
                "verbose_name_plural": "Appointment Cancellation requests",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="Reasons",
            field=models.ManyToManyField(blank=True, to="bookings.reasons"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="booker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_booker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookings.services"
            ),
        ),
    ]
