# Generated by Django 3.1.4 on 2022-08-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='userservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='bookings.services'),
        ),
    ]
